<?php
include ('../includes/check_mobile.inc.php'); 
include ('../includes/plug-ins.inc.php'); 
$imageSrc = "../images/";
?>
<html>
<head>
<?php if ($printBrowser == "IE") { ?>
<script language="JavaScript">
<!--
self.moveTo(0,0);
self.resizeTo(screen.availWidth, 750);
-->
</script>
<?php } ?>
<title>BrewBlog Reference</title>
<link href="../css/html_elements.css" rel="stylesheet" type="text/css">
<link href="../css/universal_elements.css" rel="stylesheet" type="text/css">
<link href="../css/reference.css" rel="stylesheet" type="text/css">
</head>
<body>
<div id="wideWrapperReference">		
   	<div id="referenceHeader">Typical CO<sub>2</sub> Saturation by Style (in volumes)</div>
  		<table class="dataTable">
	    <tr>
   			<td class="dataLabelLeft">English Ales</td>
	    	<td class="data" nowrap>1.5 - 2.0</td>
   			<td class="data" nowrap>&nbsp;</td>
   			<td class="dataLabel">European Lagers</td>
   		    <td class="data" nowrap>2.2 - 2.7</td>
  		</tr>
  		<tr>
   			<td class="dataLabelLeft">Stout/Porter</td>
		  	<td class="data" nowrap>1.7 - 2.3</td>
   			<td class="data" nowrap>&nbsp;</td>
   			<td class="dataLabel">American Ales/Lagers</td>
		  	<td class="data" nowrap>2.2 - 2.7</td>
  		</tr>
  		<tr>
   			<td class="dataLabelLeft">Belgian Ales</td>
		    <td class="data" nowrap>1.9 - 2.4</td>
   			<td class="data" nowrap>&nbsp;</td>
   			<td class="dataLabel">Lambic</td>
		    <td class="data" nowrap>2.4 - 2.8</td>
  		</tr>
  		<tr>
   			<td class="dataLabelLeft">Wheat Beer</td>
		    <td class="data" nowrap>3.3 - 4.5</td>
   			<td class="data" nowrap>&nbsp;</td>
   			<td class="dataLabel">Fruit Lambic</td>
		    <td class="data" nowrap>3.0 - 4.5</td>
        </tr>
  		</table>
		<table class="carbonationTable" style="text-align: left;">
	    <tr>
			<td><p>A very special thanks to Dennis Collins, inventor of the <a href="http://sdcollins.home.mindspring.com/index.html" target="_blank"><strong>HERMIT Brewery</strong></a>, for the information presented here. It is derived from his very complete <a href="http://sdcollins.home.mindspring.com/ForceCarbonation.html" target="_blank"><strong>Carbonation Chart</strong></a> Excel spreadsheet. Also thanks to the <strong>Powers Home Brewery</strong> for the C0<sub>2</sub> volume ranges.</p></td>
		</tr>
		</table>
 <div id="referenceHeader">Pressure (PSI)</div>
	<table class="carbonationTable">
    <tr>
      <td>(&deg;F)</td>
      <td class="text_9_bold bdr1L_mid">1</td>
      <td class="text_9_bold bdr1L_mid">2</td>
      <td class="text_9_bold bdr1L_mid">3</td>
      <td class="text_9_bold bdr1L_mid">4</td>
      <td class="text_9_bold bdr1L_mid">5</td>
      <td class="text_9_bold bdr1L_mid">6</td>
      <td class="text_9_bold bdr1L_mid">7</td>
      <td class="text_9_bold bdr1L_mid">8</td>
      <td class="text_9_bold bdr1L_mid">9</td>
      <td class="text_9_bold bdr1L_mid">10</td>
      <td class="text_9_bold bdr1L_mid">11</td>
      <td class="text_9_bold bdr1L_mid">12</td>
      <td class="text_9_bold bdr1L_mid">13</td>
      <td class="text_9_bold bdr1L_mid">14</td>
      <td class="text_9_bold bdr1L_mid">15</td>
      <td class="text_9_bold bdr1L_mid">16</td>
      <td class="text_9_bold bdr1L_mid">17</td>
      <td class="text_9_bold bdr1L_mid">18</td>
      <td class="text_9_bold bdr1L_mid">19</td>
      <td class="text_9_bold bdr1L_mid">20</td>
      <td class="text_9_bold bdr1L_mid">21</td>
      <td class="text_9_bold bdr1L_mid">22</td>
      <td class="text_9_bold bdr1L_mid">23</td>
      <td class="text_9_bold bdr1L_mid">24</td>
      <td class="text_9_bold bdr1L_mid">25</td>
      <td class="text_9_bold bdr1L_mid">26</td>
      <td class="text_9_bold bdr1L_mid">27</td>
      <td class="text_9_bold bdr1L_mid">28</td>
      <td class="text_9_bold bdr1L_mid">29</td>
      <td class="text_9_bold bdr1L_mid">30</td>
    </tr>
    <tr class="bknd_ultra_lt">
      <td class="text_9_bold">30</td>
      <td class="bdr1L_mid">1.82</td>
      <td class="bdr1L_mid">1.92</td>
      <td class="bdr1L_mid">2.03</td>
      <td class="bdr1L_mid">2.14</td>
      <td class="bdr1L_mid">2.23</td>
      <td class="bdr1L_mid">2.36</td>
      <td class="bdr1L_mid">2.48</td>
      <td class="bdr1L_mid">2.60</td>
      <td class="bdr1L_mid">2.70</td>
      <td class="bdr1L_mid">2.82</td>
      <td class="bdr1L_mid">2.93</td>
      <td class="bdr1L_mid">3.02</td>
      <td class="bdr1L_mid">3.13</td>
      <td class="bdr1L_mid">3.24</td>
      <td class="bdr1L_mid">3.35</td>
      <td class="bdr1L_mid">3.46</td>
      <td class="bdr1L_mid">3.57</td>
      <td class="bdr1L_mid">3.67</td>
      <td class="bdr1L_mid">3.78</td>
      <td class="bdr1L_mid">3.89</td>
      <td class="bdr1L_mid">4.00</td>
      <td class="bdr1L_mid">4.11</td>
      <td class="bdr1L_mid">4.22</td>
      <td class="bdr1L_mid">4.33</td>
      <td class="bdr1L_mid">4.44</td>
      <td class="bdr1L_mid">4.55</td>
      <td class="bdr1L_mid">4.66</td>
      <td class="bdr1L_mid">4.77</td>
      <td class="bdr1L_mid">4.87</td>
      <td class="bdr1L_mid">4.98</td>
    </tr>
    <tr>
      <td class="text_9_bold">31</td>
      <td class="bdr1L_mid">1.78</td>
      <td class="bdr1L_mid">1.88</td>
      <td class="bdr1L_mid">2.00</td>
      <td class="bdr1L_mid">2.10</td>
      <td class="bdr1L_mid">2.20</td>
      <td class="bdr1L_mid">2.31</td>
      <td class="bdr1L_mid">2.42</td>
      <td class="bdr1L_mid">2.54</td>
      <td class="bdr1L_mid">2.65</td>
      <td class="bdr1L_mid">2.76</td>
      <td class="bdr1L_mid">2.86</td>
      <td class="bdr1L_mid">2.96</td>
      <td class="bdr1L_mid">3.07</td>
      <td class="bdr1L_mid">3.17</td>
      <td class="bdr1L_mid">3.28</td>
      <td class="bdr1L_mid">3.39</td>
      <td class="bdr1L_mid">3.50</td>
      <td class="bdr1L_mid">3.60</td>
      <td class="bdr1L_mid">3.71</td>
      <td class="bdr1L_mid">3.82</td>
      <td class="bdr1L_mid">3.93</td>
      <td class="bdr1L_mid">4.03</td>
      <td class="bdr1L_mid">4.14</td>
      <td class="bdr1L_mid">4.25</td>
      <td class="bdr1L_mid">4.35</td>
      <td class="bdr1L_mid">4.46</td>
      <td class="bdr1L_mid">4.57</td>
      <td class="bdr1L_mid">4.68</td>
      <td class="bdr1L_mid">4.78</td>
      <td class="bdr1L_mid">4.89</td>
    </tr>
    <tr class="bknd_ultra_lt">
      <td class="text_9_bold">32</td>
      <td class="bdr1L_mid">1.75</td>
      <td class="bdr1L_mid">1.85</td>
      <td class="bdr1L_mid">1.95</td>
      <td class="bdr1L_mid">2.05</td>
      <td class="bdr1L_mid">2.15</td>
      <td class="bdr1L_mid">2.27</td>
      <td class="bdr1L_mid">2.38</td>
      <td class="bdr1L_mid">2.48</td>
      <td class="bdr1L_mid">2.59</td>
      <td class="bdr1L_mid">2.70</td>
      <td class="bdr1L_mid">2.80</td>
      <td class="bdr1L_mid">2.90</td>
      <td class="bdr1L_mid">3.00</td>
      <td class="bdr1L_mid">3.11</td>
      <td class="bdr1L_mid">3.21</td>
      <td class="bdr1L_mid">3.31</td>
      <td class="bdr1L_mid">3.42</td>
      <td class="bdr1L_mid">3.52</td>
      <td class="bdr1L_mid">3.63</td>
      <td class="bdr1L_mid">3.73</td>
      <td class="bdr1L_mid">3.84</td>
      <td class="bdr1L_mid">3.94</td>
      <td class="bdr1L_mid">4.04</td>
      <td class="bdr1L_mid">4.15</td>
      <td class="bdr1L_mid">4.25</td>
      <td class="bdr1L_mid">4.36</td>
      <td class="bdr1L_mid">4.46</td>
      <td class="bdr1L_mid">4.57</td>
      <td class="bdr1L_mid">4.67</td>
      <td class="bdr1L_mid">4.77</td>
    </tr>
    <tr>
      <td class="text_9_bold">33</td>
      <td class="bdr1L_mid">1.71</td>
      <td class="bdr1L_mid">1.81</td>
      <td class="bdr1L_mid">1.91</td>
      <td class="bdr1L_mid">2.01</td>
      <td class="bdr1L_mid">2.10</td>
      <td class="bdr1L_mid">2.23</td>
      <td class="bdr1L_mid">2.33</td>
      <td class="bdr1L_mid">2.43</td>
      <td class="bdr1L_mid">2.53</td>
      <td class="bdr1L_mid">2.63</td>
      <td class="bdr1L_mid">2.74</td>
      <td class="bdr1L_mid">2.84</td>
      <td class="bdr1L_mid">2.96</td>
      <td class="bdr1L_mid">3.06</td>
      <td class="bdr1L_mid">3.15</td>
      <td class="bdr1L_mid">3.25</td>
      <td class="bdr1L_mid">3.35</td>
      <td class="bdr1L_mid">3.46</td>
      <td class="bdr1L_mid">3.56</td>
      <td class="bdr1L_mid">3.66</td>
      <td class="bdr1L_mid">3.76</td>
      <td class="bdr1L_mid">3.87</td>
      <td class="bdr1L_mid">3.97</td>
      <td class="bdr1L_mid">4.07</td>
      <td class="bdr1L_mid">4.18</td>
      <td class="bdr1L_mid">4.28</td>
      <td class="bdr1L_mid">4.38</td>
      <td class="bdr1L_mid">4.48</td>
      <td class="bdr1L_mid">4.59</td>
      <td class="bdr1L_mid">4.69</td>
    </tr>
    <tr class="bknd_ultra_lt">
      <td class="text_9_bold">34</td>
      <td class="bdr1L_mid">1.68</td>
      <td class="bdr1L_mid">1.78</td>
      <td class="bdr1L_mid">1.86</td>
      <td class="bdr1L_mid">1.97</td>
      <td class="bdr1L_mid">2.06</td>
      <td class="bdr1L_mid">2.18</td>
      <td class="bdr1L_mid">2.28</td>
      <td class="bdr1L_mid">2.38</td>
      <td class="bdr1L_mid">2.48</td>
      <td class="bdr1L_mid">2.58</td>
      <td class="bdr1L_mid">2.69</td>
      <td class="bdr1L_mid">2.79</td>
      <td class="bdr1L_mid">2.90</td>
      <td class="bdr1L_mid">3.00</td>
      <td class="bdr1L_mid">3.09</td>
      <td class="bdr1L_mid">3.19</td>
      <td class="bdr1L_mid">3.29</td>
      <td class="bdr1L_mid">3.39</td>
      <td class="bdr1L_mid">3.49</td>
      <td class="bdr1L_mid">3.59</td>
      <td class="bdr1L_mid">3.69</td>
      <td class="bdr1L_mid">3.79</td>
      <td class="bdr1L_mid">3.90</td>
      <td class="bdr1L_mid">4.00</td>
      <td class="bdr1L_mid">4.10</td>
      <td class="bdr1L_mid">4.20</td>
      <td class="bdr1L_mid">4.30</td>
      <td class="bdr1L_mid">4.40</td>
      <td class="bdr1L_mid">4.50</td>
      <td class="bdr1L_mid">4.60</td>
    </tr>
    <tr>
      <td class="text_9_bold">35</td>
      <td class="bdr1L_mid">1.63</td>
      <td class="bdr1L_mid">1.73</td>
      <td class="bdr1L_mid">1.83</td>
      <td class="bdr1L_mid">1.93</td>
      <td class="bdr1L_mid">2.02</td>
      <td class="bdr1L_mid">2.14</td>
      <td class="bdr1L_mid">2.24</td>
      <td class="bdr1L_mid">2.34</td>
      <td class="bdr1L_mid">2.43</td>
      <td class="bdr1L_mid">2.52</td>
      <td class="bdr1L_mid">2.63</td>
      <td class="bdr1L_mid">2.73</td>
      <td class="bdr1L_mid">2.83</td>
      <td class="bdr1L_mid">2.93</td>
      <td class="bdr1L_mid">3.02</td>
      <td class="bdr1L_mid">3.12</td>
      <td class="bdr1L_mid">3.22</td>
      <td class="bdr1L_mid">3.32</td>
      <td class="bdr1L_mid">3.42</td>
      <td class="bdr1L_mid">3.52</td>
      <td class="bdr1L_mid">3.62</td>
      <td class="bdr1L_mid">3.72</td>
      <td class="bdr1L_mid">3.82</td>
      <td class="bdr1L_mid">3.92</td>
      <td class="bdr1L_mid">4.01</td>
      <td class="bdr1L_mid">4.11</td>
      <td class="bdr1L_mid">4.21</td>
      <td class="bdr1L_mid">4.31</td>
      <td class="bdr1L_mid">4.41</td>
      <td class="bdr1L_mid">4.51</td>
    </tr>
    <tr class="bknd_ultra_lt">
      <td class="text_9_bold">36</td>
      <td class="bdr1L_mid">1.60</td>
      <td class="bdr1L_mid">1.69</td>
      <td class="bdr1L_mid">1.79</td>
      <td class="bdr1L_mid">1.88</td>
      <td class="bdr1L_mid">1.98</td>
      <td class="bdr1L_mid">2.09</td>
      <td class="bdr1L_mid">2.19</td>
      <td class="bdr1L_mid">2.29</td>
      <td class="bdr1L_mid">2.38</td>
      <td class="bdr1L_mid">2.47</td>
      <td class="bdr1L_mid">2.57</td>
      <td class="bdr1L_mid">2.67</td>
      <td class="bdr1L_mid">2.77</td>
      <td class="bdr1L_mid">2.86</td>
      <td class="bdr1L_mid">2.96</td>
      <td class="bdr1L_mid">3.05</td>
      <td class="bdr1L_mid">3.15</td>
      <td class="bdr1L_mid">3.24</td>
      <td class="bdr1L_mid">3.34</td>
      <td class="bdr1L_mid">3.43</td>
      <td class="bdr1L_mid">3.53</td>
      <td class="bdr1L_mid">3.63</td>
      <td class="bdr1L_mid">3.72</td>
      <td class="bdr1L_mid">3.82</td>
      <td class="bdr1L_mid">3.92</td>
      <td class="bdr1L_mid">4.01</td>
      <td class="bdr1L_mid">4.11</td>
      <td class="bdr1L_mid">4.21</td>
      <td class="bdr1L_mid">4.30</td>
      <td class="bdr1L_mid">4.40</td>
    </tr>
    <tr>
      <td class="text_9_bold">37</td>
      <td class="bdr1L_mid">1.55</td>
      <td class="bdr1L_mid">1.65</td>
      <td class="bdr1L_mid">1.74</td>
      <td class="bdr1L_mid">1.84</td>
      <td class="bdr1L_mid">1.94</td>
      <td class="bdr1L_mid">2.04</td>
      <td class="bdr1L_mid">2.14</td>
      <td class="bdr1L_mid">2.24</td>
      <td class="bdr1L_mid">2.33</td>
      <td class="bdr1L_mid">2.42</td>
      <td class="bdr1L_mid">2.52</td>
      <td class="bdr1L_mid">2.62</td>
      <td class="bdr1L_mid">2.71</td>
      <td class="bdr1L_mid">2.80</td>
      <td class="bdr1L_mid">2.90</td>
      <td class="bdr1L_mid">3.00</td>
      <td class="bdr1L_mid">3.09</td>
      <td class="bdr1L_mid">3.18</td>
      <td class="bdr1L_mid">3.27</td>
      <td class="bdr1L_mid">3.37</td>
      <td class="bdr1L_mid">3.46</td>
      <td class="bdr1L_mid">3.56</td>
      <td class="bdr1L_mid">3.65</td>
      <td class="bdr1L_mid">3.75</td>
      <td class="bdr1L_mid">3.84</td>
     <td class="bdr1L_mid">3.94</td>
      <td class="bdr1L_mid">4.03</td>
      <td class="bdr1L_mid">4.13</td>
      <td class="bdr1L_mid">4.22</td>
      <td class="bdr1L_mid">4.32</td>
    </tr>
    <tr class="bknd_ultra_lt">
      <td class="text_9_bold">38</td>
      <td class="bdr1L_mid">1.52</td>
      <td class="bdr1L_mid">1.61</td>
      <td class="bdr1L_mid">1.71</td>
      <td class="bdr1L_mid">1.80</td>
      <td class="bdr1L_mid">1.90</td>
      <td class="bdr1L_mid">2.00</td>
      <td class="bdr1L_mid">2.10</td>
      <td class="bdr1L_mid">2.20</td>
      <td class="bdr1L_mid">2.29</td>
      <td class="bdr1L_mid">2.38</td>
      <td class="bdr1L_mid">2.48</td>
      <td class="bdr1L_mid">2.57</td>
      <td class="bdr1L_mid">2.66</td>
      <td class="bdr1L_mid">2.75</td>
      <td class="bdr1L_mid">2.85</td>
      <td class="bdr1L_mid">2.94</td>
      <td class="bdr1L_mid">3.03</td>
      <td class="bdr1L_mid">3.12</td>
      <td class="bdr1L_mid">3.21</td>
      <td class="bdr1L_mid">3.30</td>
      <td class="bdr1L_mid">3.40</td>
      <td class="bdr1L_mid">3.49</td>
      <td class="bdr1L_mid">3.59</td>
      <td class="bdr1L_mid">3.68</td>
      <td class="bdr1L_mid">3.77</td>
      <td class="bdr1L_mid">3.87</td>
      <td class="bdr1L_mid">3.96</td>
      <td class="bdr1L_mid">4.06</td>
      <td class="bdr1L_mid">4.15</td>
      <td class="bdr1L_mid">4.24</td>
    </tr>
    <tr>
      <td class="text_9_bold">39</td>
      <td class="bdr1L_mid">1.49</td>
      <td class="bdr1L_mid">1.58</td>
      <td class="bdr1L_mid">1.67</td>
      <td class="bdr1L_mid">1.77</td>
      <td class="bdr1L_mid">1.86</td>
      <td class="bdr1L_mid">1.96</td>
      <td class="bdr1L_mid">2.06</td>
      <td class="bdr1L_mid">2.15</td>
      <td class="bdr1L_mid">2.25</td>
      <td class="bdr1L_mid">2.34</td>
      <td class="bdr1L_mid">2.43</td>
      <td class="bdr1L_mid">2.52</td>
      <td class="bdr1L_mid">2.61</td>
      <td class="bdr1L_mid">2.70</td>
      <td class="bdr1L_mid">2.80</td>
      <td class="bdr1L_mid">2.89</td>
      <td class="bdr1L_mid">2.98</td>
      <td class="bdr1L_mid">3.07</td>
      <td class="bdr1L_mid">3.16</td>
      <td class="bdr1L_mid">3.25</td>
      <td class="bdr1L_mid">3.34</td>
      <td class="bdr1L_mid">3.44</td>
      <td class="bdr1L_mid">3.53</td>
      <td class="bdr1L_mid">3.62</td>
      <td class="bdr1L_mid">3.71</td>
      <td class="bdr1L_mid">3.81</td>
      <td class="bdr1L_mid">3.90</td>
      <td class="bdr1L_mid">3.99</td>
      <td class="bdr1L_mid">4.08</td>
      <td class="bdr1L_mid">4.18</td>
    </tr>
    <tr class="bknd_ultra_lt">
      <td class="text_9_bold">40</td>
      <td class="bdr1L_mid">1.47</td>
      <td class="bdr1L_mid">1.56</td>
      <td class="bdr1L_mid">1.65</td>
      <td class="bdr1L_mid">1.74</td>
      <td class="bdr1L_mid">1.83</td>
      <td class="bdr1L_mid">1.92</td>
      <td class="bdr1L_mid">2.01</td>
      <td class="bdr1L_mid">2.10</td>
      <td class="bdr1L_mid">2.20</td>
      <td class="bdr1L_mid">2.30</td>
      <td class="bdr1L_mid">2.39</td>
      <td class="bdr1L_mid">2.47</td>
      <td class="bdr1L_mid">2.56</td>
      <td class="bdr1L_mid">2.65</td>
      <td class="bdr1L_mid">2.75</td>
      <td class="bdr1L_mid">2.84</td>
      <td class="bdr1L_mid">2.93</td>
      <td class="bdr1L_mid">3.01</td>
      <td class="bdr1L_mid">3.10</td>
      <td class="bdr1L_mid">3.19</td>
      <td class="bdr1L_mid">3.28</td>
      <td class="bdr1L_mid">3.37</td>
      <td class="bdr1L_mid">3.46</td>
      <td class="bdr1L_mid">3.55</td>
      <td class="bdr1L_mid">3.64</td>
      <td class="bdr1L_mid">3.73</td>
      <td class="bdr1L_mid">3.82</td>
      <td class="bdr1L_mid">3.91</td>
      <td class="bdr1L_mid">4.01</td>
      <td class="bdr1L_mid">4.10</td>
    </tr>
    <tr>
      <td class="text_9_bold">41</td>
      <td class="bdr1L_mid">1.43</td>
      <td class="bdr1L_mid">1.52</td>
      <td class="bdr1L_mid">1.61</td>
      <td class="bdr1L_mid">1.70</td>
      <td class="bdr1L_mid">1.79</td>
      <td class="bdr1L_mid">1.88</td>
      <td class="bdr1L_mid">1.97</td>
      <td class="bdr1L_mid">2.06</td>
      <td class="bdr1L_mid">2.16</td>
      <td class="bdr1L_mid">2.25</td>
      <td class="bdr1L_mid">2.34</td>
      <td class="bdr1L_mid">2.43</td>
      <td class="bdr1L_mid">2.52</td>
      <td class="bdr1L_mid">2.60</td>
      <td class="bdr1L_mid">2.70</td>
      <td class="bdr1L_mid">2.79</td>
      <td class="bdr1L_mid">2.88</td>
      <td class="bdr1L_mid">2.96</td>
      <td class="bdr1L_mid">3.05</td>
      <td class="bdr1L_mid">3.14</td>
      <td class="bdr1L_mid">3.23</td>
      <td class="bdr1L_mid">3.32</td>
      <td class="bdr1L_mid">3.41</td>
      <td class="bdr1L_mid">3.50</td>
      <td class="bdr1L_mid">3.59</td>
      <td class="bdr1L_mid">3.68</td>
      <td class="bdr1L_mid">3.77</td>
      <td class="bdr1L_mid">3.86</td>
      <td class="bdr1L_mid">3.95</td>
      <td class="bdr1L_mid">4.04</td>
    </tr>
    <tr class="bknd_ultra_lt">
      <td class="text_9_bold">42</td>
      <td class="bdr1L_mid">1.39</td>
      <td class="bdr1L_mid">1.48</td>
      <td class="bdr1L_mid">1.57</td>
      <td class="bdr1L_mid">1.66</td>
      <td class="bdr1L_mid">1.75</td>
      <td class="bdr1L_mid">1.85</td>
      <td class="bdr1L_mid">1.94</td>
      <td class="bdr1L_mid">2.02</td>
      <td class="bdr1L_mid">2.12</td>
      <td class="bdr1L_mid">2.21</td>
      <td class="bdr1L_mid">2.30</td>
      <td class="bdr1L_mid">2.39</td>
      <td class="bdr1L_mid">2.48</td>
      <td class="bdr1L_mid">2.56</td>
      <td class="bdr1L_mid">2.65</td>
      <td class="bdr1L_mid">2.74</td>
      <td class="bdr1L_mid">2.83</td>
      <td class="bdr1L_mid">2.91</td>
      <td class="bdr1L_mid">3.00</td>
      <td class="bdr1L_mid">3.09</td>
      <td class="bdr1L_mid">3.18</td>
      <td class="bdr1L_mid">3.26</td>
      <td class="bdr1L_mid">3.35</td>
      <td class="bdr1L_mid">3.44</td>
      <td class="bdr1L_mid">3.53</td>
      <td class="bdr1L_mid">3.62</td>
      <td class="bdr1L_mid">3.70</td>
      <td class="bdr1L_mid">3.79</td>
      <td class="bdr1L_mid">3.88</td>
      <td class="bdr1L_mid">3.97</td>
    </tr>
    <tr>
      <td class="text_9_bold">43</td>
      <td class="bdr1L_mid">1.37</td>
      <td class="bdr1L_mid">1.46</td>
      <td class="bdr1L_mid">1.54</td>
      <td class="bdr1L_mid">1.63</td>
      <td class="bdr1L_mid">1.72</td>
      <td class="bdr1L_mid">1.81</td>
      <td class="bdr1L_mid">1.90</td>
      <td class="bdr1L_mid">1.99</td>
      <td class="bdr1L_mid">2.08</td>
      <td class="bdr1L_mid">2.17</td>
      <td class="bdr1L_mid">2.26</td>
      <td class="bdr1L_mid">2.34</td>
      <td class="bdr1L_mid">2.43</td>
      <td class="bdr1L_mid">2.52</td>
      <td class="bdr1L_mid">2.61</td>
      <td class="bdr1L_mid">2.69</td>
      <td class="bdr1L_mid">2.78</td>
      <td class="bdr1L_mid">2.86</td>
      <td class="bdr1L_mid">2.95</td>
      <td class="bdr1L_mid">3.04</td>
      <td class="bdr1L_mid">3.13</td>
      <td class="bdr1L_mid">3.21</td>
      <td class="bdr1L_mid">3.30</td>
      <td class="bdr1L_mid">3.39</td>
      <td class="bdr1L_mid">3.47</td>
      <td class="bdr1L_mid">3.56</td>
      <td class="bdr1L_mid">3.65</td>
      <td class="bdr1L_mid">3.74</td>
      <td class="bdr1L_mid">3.82</td>
      <td class="bdr1L_mid">3.91</td>
    </tr>
    <tr class="bknd_ultra_lt">
      <td class="text_9_bold">44</td>
      <td class="bdr1L_mid">1.35</td>
      <td class="bdr1L_mid">1.43</td>
      <td class="bdr1L_mid">1.52</td>
      <td class="bdr1L_mid">1.60</td>
      <td class="bdr1L_mid">1.69</td>
      <td class="bdr1L_mid">1.78</td>
      <td class="bdr1L_mid">1.87</td>
      <td class="bdr1L_mid">1.95</td>
      <td class="bdr1L_mid">2.04</td>
      <td class="bdr1L_mid">2.13</td>
      <td class="bdr1L_mid">2.22</td>
      <td class="bdr1L_mid">2.30</td>
      <td class="bdr1L_mid">2.39</td>
      <td class="bdr1L_mid">2.47</td>
      <td class="bdr1L_mid">2.56</td>
      <td class="bdr1L_mid">2.64</td>
      <td class="bdr1L_mid">2.73</td>
      <td class="bdr1L_mid">2.81</td>
      <td class="bdr1L_mid">2.90</td>
      <td class="bdr1L_mid">2.99</td>
      <td class="bdr1L_mid">3.07</td>
      <td class="bdr1L_mid">3.10</td>
      <td class="bdr1L_mid">3.24</td>
      <td class="bdr1L_mid">3.33</td>
      <td class="bdr1L_mid">3.41</td>
      <td class="bdr1L_mid">3.50</td>
      <td class="bdr1L_mid">3.58</td>
      <td class="bdr1L_mid">3.67</td>
      <td class="bdr1L_mid">3.76</td>
      <td class="bdr1L_mid">3.84</td>
    </tr>
    <tr>
      <td class="text_9_bold">45</td>
      <td class="bdr1L_mid">1.32</td>
      <td class="bdr1L_mid">1.41</td>
      <td class="bdr1L_mid">1.49</td>
      <td class="bdr1L_mid">1.58</td>
      <td class="bdr1L_mid">1.66</td>
      <td class="bdr1L_mid">1.75</td>
      <td class="bdr1L_mid">1.84</td>
      <td class="bdr1L_mid">1.91</td>
      <td class="bdr1L_mid">2.00</td>
      <td class="bdr1L_mid">2.08</td>
      <td class="bdr1L_mid">2.17</td>
      <td class="bdr1L_mid">2.26</td>
      <td class="bdr1L_mid">2.34</td>
      <td class="bdr1L_mid">2.42</td>
      <td class="bdr1L_mid">2.51</td>
      <td class="bdr1L_mid">2.60</td>
      <td class="bdr1L_mid">2.69</td>
      <td class="bdr1L_mid">2.77</td>
      <td class="bdr1L_mid">2.86</td>
      <td class="bdr1L_mid">2.94</td>
      <td class="bdr1L_mid">3.02</td>
      <td class="bdr1L_mid">3.11</td>
      <td class="bdr1L_mid">3.19</td>
      <td class="bdr1L_mid">3.28</td>
      <td class="bdr1L_mid">3.36</td>
      <td class="bdr1L_mid">3.45</td>
      <td class="bdr1L_mid">3.53</td>
      <td class="bdr1L_mid">3.62</td>
      <td class="bdr1L_mid">3.70</td>
      <td class="bdr1L_mid">3.79</td>
    </tr>
    <tr class="bknd_ultra_lt">
      <td class="text_9_bold">46</td>
      <td class="bdr1L_mid">1.28</td>
      <td class="bdr1L_mid">1.37</td>
      <td class="bdr1L_mid">1.45</td>
      <td class="bdr1L_mid">1.54</td>
      <td class="bdr1L_mid">1.62</td>
      <td class="bdr1L_mid">1.71</td>
      <td class="bdr1L_mid">1.80</td>
      <td class="bdr1L_mid">1.88</td>
      <td class="bdr1L_mid">1.96</td>
      <td class="bdr1L_mid">2.04</td>
      <td class="bdr1L_mid">2.13</td>
      <td class="bdr1L_mid">2.22</td>
      <td class="bdr1L_mid">2.30</td>
      <td class="bdr1L_mid">2.38</td>
      <td class="bdr1L_mid">2.47</td>
      <td class="bdr1L_mid">2.55</td>
      <td class="bdr1L_mid">2.64</td>
      <td class="bdr1L_mid">2.72</td>
      <td class="bdr1L_mid">2.81</td>
      <td class="bdr1L_mid">2.89</td>
      <td class="bdr1L_mid">2.98</td>
      <td class="bdr1L_mid">3.06</td>
      <td class="bdr1L_mid">3.15</td>
      <td class="bdr1L_mid">3.23</td>
      <td class="bdr1L_mid">3.31</td>
      <td class="bdr1L_mid">3.40</td>
      <td class="bdr1L_mid">3.48</td>
      <td class="bdr1L_mid">3.57</td>
      <td class="bdr1L_mid">3.65</td>
      <td class="bdr1L_mid">3.74</td>
    </tr>
    <tr>
      <td class="text_9_bold">47</td>
      <td class="bdr1L_mid">1.26</td>
      <td class="bdr1L_mid">1.34</td>
      <td class="bdr1L_mid">1.42</td>
      <td class="bdr1L_mid">1.51</td>
      <td class="bdr1L_mid">1.59</td>
      <td class="bdr1L_mid">1.68</td>
      <td class="bdr1L_mid">1.76</td>
      <td class="bdr1L_mid">1.84</td>
      <td class="bdr1L_mid">1.92</td>
      <td class="bdr1L_mid">2.00</td>
      <td class="bdr1L_mid">2.09</td>
      <td class="bdr1L_mid">2.18</td>
      <td class="bdr1L_mid">2.26</td>
      <td class="bdr1L_mid">2.34</td>
      <td class="bdr1L_mid">2.42</td>
      <td class="bdr1L_mid">2.50</td>
      <td class="bdr1L_mid">2.59</td>
      <td class="bdr1L_mid">2.67</td>
      <td class="bdr1L_mid">2.76</td>
      <td class="bdr1L_mid">2.84</td>
      <td class="bdr1L_mid">2.93</td>
      <td class="bdr1L_mid">3.02</td>
      <td class="bdr1L_mid">3.09</td>
      <td class="bdr1L_mid">3.18</td>
      <td class="bdr1L_mid">3.26</td>
      <td class="bdr1L_mid">3.35</td>
      <td class="bdr1L_mid">3.43</td>
      <td class="bdr1L_mid">3.51</td>
      <td class="bdr1L_mid">3.60</td>
      <td class="bdr1L_mid">3.68</td>
    </tr>
    <tr class="bknd_ultra_lt">
      <td class="text_9_bold">48</td>
      <td class="bdr1L_mid">1.23</td>
      <td class="bdr1L_mid">1.31</td>
      <td class="bdr1L_mid">1.39</td>
      <td class="bdr1L_mid">1.48</td>
      <td class="bdr1L_mid">1.56</td>
      <td class="bdr1L_mid">1.65</td>
      <td class="bdr1L_mid">1.73</td>
      <td class="bdr1L_mid">1.81</td>
      <td class="bdr1L_mid">1.89</td>
      <td class="bdr1L_mid">1.96</td>
      <td class="bdr1L_mid">2.05</td>
      <td class="bdr1L_mid">2.14</td>
      <td class="bdr1L_mid">2.22</td>
      <td class="bdr1L_mid">2.30</td>
      <td class="bdr1L_mid">2.38</td>
      <td class="bdr1L_mid">2.46</td>
      <td class="bdr1L_mid">2.54</td>
      <td class="bdr1L_mid">2.62</td>
      <td class="bdr1L_mid">2.71</td>
      <td class="bdr1L_mid">2.79</td>
      <td class="bdr1L_mid">2.88</td>
      <td class="bdr1L_mid">2.96</td>
      <td class="bdr1L_mid">3.04</td>
      <td class="bdr1L_mid">3.13</td>
      <td class="bdr1L_mid">3.21</td>
      <td class="bdr1L_mid">3.30</td>
      <td class="bdr1L_mid">3.38</td>
      <td class="bdr1L_mid">3.46</td>
      <td class="bdr1L_mid">3.54</td>
      <td class="bdr1L_mid">3.63</td>
    </tr>
    <tr>
      <td class="text_9_bold">49</td>
      <td class="bdr1L_mid">1.21</td>
      <td class="bdr1L_mid">1.29</td>
      <td class="bdr1L_mid">1.37</td>
      <td class="bdr1L_mid">1.45</td>
      <td class="bdr1L_mid">1.53</td>
      <td class="bdr1L_mid">1.62</td>
      <td class="bdr1L_mid">1.70</td>
      <td class="bdr1L_mid">1.79</td>
      <td class="bdr1L_mid">1.86</td>
      <td class="bdr1L_mid">1.93</td>
      <td class="bdr1L_mid">2.01</td>
      <td class="bdr1L_mid">2.10</td>
      <td class="bdr1L_mid">2.18</td>
      <td class="bdr1L_mid">2.25</td>
      <td class="bdr1L_mid">2.34</td>
      <td class="bdr1L_mid">2.42</td>
      <td class="bdr1L_mid">2.50</td>
      <td class="bdr1L_mid">2.58</td>
      <td class="bdr1L_mid">2.67</td>
      <td class="bdr1L_mid">2.75</td>
      <td class="bdr1L_mid">2.83</td>
      <td class="bdr1L_mid">2.91</td>
      <td class="bdr1L_mid">3.00</td>
      <td class="bdr1L_mid">3.07</td>
      <td class="bdr1L_mid">3.15</td>
      <td class="bdr1L_mid">3.23</td>
      <td class="bdr1L_mid">3.31</td>
      <td class="bdr1L_mid">3.39</td>
      <td class="bdr1L_mid">3.47</td>
      <td class="bdr1L_mid">3.56</td>
    </tr>
    <tr class="bknd_ultra_lt">
      <td class="text_9_bold">50</td>
      <td class="bdr1L_mid">1.18</td>
      <td class="bdr1L_mid">1.26</td>
      <td class="bdr1L_mid">1.34</td>
      <td class="bdr1L_mid">1.42</td>
      <td class="bdr1L_mid">1.50</td>
      <td class="bdr1L_mid">1.59</td>
      <td class="bdr1L_mid">1.66</td>
      <td class="bdr1L_mid">1.74</td>
      <td class="bdr1L_mid">1.82</td>
      <td class="bdr1L_mid">1.90</td>
      <td class="bdr1L_mid">1.98</td>
      <td class="bdr1L_mid">2.06</td>
      <td class="bdr1L_mid">2.14</td>
      <td class="bdr1L_mid">2.21</td>
      <td class="bdr1L_mid">2.30</td>
      <td class="bdr1L_mid">2.38</td>
      <td class="bdr1L_mid">2.46</td>
      <td class="bdr1L_mid">2.54</td>
      <td class="bdr1L_mid">2.62</td>
      <td class="bdr1L_mid">2.70</td>
      <td class="bdr1L_mid">2.78</td>
      <td class="bdr1L_mid">2.86</td>
      <td class="bdr1L_mid">2.94</td>
      <td class="bdr1L_mid">3.02</td>
      <td class="bdr1L_mid">3.10</td>
      <td class="bdr1L_mid">3.17</td>
      <td class="bdr1L_mid">3.25</td>
      <td class="bdr1L_mid">3.33</td>
      <td class="bdr1L_mid">3.41</td>
      <td class="bdr1L_mid">3.49</td>
    </tr>
    <tr>
      <td class="text_9_bold">51</td>
      <td class="bdr1L_mid">1.18</td>
      <td class="bdr1L_mid">1.26</td>
      <td class="bdr1L_mid">1.34</td>
      <td class="bdr1L_mid">1.42</td>
      <td class="bdr1L_mid">1.49</td>
      <td class="bdr1L_mid">1.57</td>
      <td class="bdr1L_mid">1.64</td>
      <td class="bdr1L_mid">1.71</td>
      <td class="bdr1L_mid">1.79</td>
      <td class="bdr1L_mid">1.87</td>
      <td class="bdr1L_mid">1.95</td>
      <td class="bdr1L_mid">2.02</td>
      <td class="bdr1L_mid">2.10</td>
      <td class="bdr1L_mid">2.18</td>
      <td class="bdr1L_mid">2.26</td>
      <td class="bdr1L_mid">2.34</td>
      <td class="bdr1L_mid">2.42</td>
      <td class="bdr1L_mid">2.49</td>
      <td class="bdr1L_mid">2.57</td>
      <td class="bdr1L_mid">2.65</td>
      <td class="bdr1L_mid">2.74</td>
      <td class="bdr1L_mid">2.82</td>
      <td class="bdr1L_mid">2.90</td>
      <td class="bdr1L_mid">2.97</td>
      <td class="bdr1L_mid">3.05</td>
      <td class="bdr1L_mid">3.13</td>
      <td class="bdr1L_mid">3.19</td>
      <td class="bdr1L_mid">3.27</td>
      <td class="bdr1L_mid">3.34</td>
      <td class="bdr1L_mid">3.42</td>
    </tr>
    <tr class="bknd_ultra_lt">
      <td class="text_9_bold">52</td>
      <td class="bdr1L_mid">1.16</td>
      <td class="bdr1L_mid">1.23</td>
      <td class="bdr1L_mid">1.31</td>
      <td class="bdr1L_mid">1.39</td>
      <td class="bdr1L_mid">1.46</td>
      <td class="bdr1L_mid">1.54</td>
      <td class="bdr1L_mid">1.61</td>
      <td class="bdr1L_mid">1.68</td>
      <td class="bdr1L_mid">1.76</td>
      <td class="bdr1L_mid">1.84</td>
      <td class="bdr1L_mid">1.92</td>
      <td class="bdr1L_mid">1.99</td>
      <td class="bdr1L_mid">2.06</td>
      <td class="bdr1L_mid">2.14</td>
      <td class="bdr1L_mid">2.22</td>
      <td class="bdr1L_mid">2.30</td>
      <td class="bdr1L_mid">2.38</td>
      <td class="bdr1L_mid">2.45</td>
      <td class="bdr1L_mid">2.53</td>
      <td class="bdr1L_mid">2.61</td>
      <td class="bdr1L_mid">2.68</td>
      <td class="bdr1L_mid">2.76</td>
      <td class="bdr1L_mid">2.84</td>
      <td class="bdr1L_mid">2.92</td>
      <td class="bdr1L_mid">3.00</td>
      <td class="bdr1L_mid">3.06</td>
      <td class="bdr1L_mid">3.13</td>
      <td class="bdr1L_mid">3.22</td>
      <td class="bdr1L_mid">3.30</td>
      <td class="bdr1L_mid">3.37</td>
    </tr>
    <tr>
      <td class="text_9_bold">53</td>
      <td class="bdr1L_mid">1.14</td>
      <td class="bdr1L_mid">1.21</td>
      <td class="bdr1L_mid">1.29</td>
      <td class="bdr1L_mid">1.36</td>
      <td class="bdr1L_mid">1.44</td>
      <td class="bdr1L_mid">1.51</td>
      <td class="bdr1L_mid">1.59</td>
      <td class="bdr1L_mid">1.66</td>
      <td class="bdr1L_mid">1.74</td>
      <td class="bdr1L_mid">1.81</td>
      <td class="bdr1L_mid">1.89</td>
      <td class="bdr1L_mid">1.96</td>
      <td class="bdr1L_mid">2.03</td>
      <td class="bdr1L_mid">2.10</td>
      <td class="bdr1L_mid">2.18</td>
      <td class="bdr1L_mid">2.26</td>
      <td class="bdr1L_mid">2.34</td>
      <td class="bdr1L_mid">2.41</td>
      <td class="bdr1L_mid">2.49</td>
      <td class="bdr1L_mid">2.57</td>
      <td class="bdr1L_mid">2.64</td>
      <td class="bdr1L_mid">2.71</td>
      <td class="bdr1L_mid">2.79</td>
      <td class="bdr1L_mid">2.86</td>
      <td class="bdr1L_mid">2.94</td>
      <td class="bdr1L_mid">3.01</td>
      <td class="bdr1L_mid">3.09</td>
      <td class="bdr1L_mid">3.16</td>
      <td class="bdr1L_mid">3.24</td>
      <td class="bdr1L_mid">3.31</td>
    </tr>
    <tr class="bknd_ultra_lt">
      <td class="text_9_bold">54</td>
      <td class="bdr1L_mid">1.12</td>
      <td class="bdr1L_mid">1.19</td>
      <td class="bdr1L_mid">1.27</td>
      <td class="bdr1L_mid">1.34</td>
      <td class="bdr1L_mid">1.41</td>
      <td class="bdr1L_mid">1.49</td>
      <td class="bdr1L_mid">1.56</td>
      <td class="bdr1L_mid">1.63</td>
      <td class="bdr1L_mid">1.71</td>
      <td class="bdr1L_mid">1.78</td>
      <td class="bdr1L_mid">1.86</td>
      <td class="bdr1L_mid">1.93</td>
      <td class="bdr1L_mid">2.00</td>
      <td class="bdr1L_mid">2.07</td>
      <td class="bdr1L_mid">2.15</td>
      <td class="bdr1L_mid">2.22</td>
      <td class="bdr1L_mid">2.30</td>
      <td class="bdr1L_mid">2.37</td>
      <td class="bdr1L_mid">2.45</td>
      <td class="bdr1L_mid">2.52</td>
      <td class="bdr1L_mid">2.59</td>
      <td class="bdr1L_mid">2.66</td>
      <td class="bdr1L_mid">2.74</td>
      <td class="bdr1L_mid">2.81</td>
      <td class="bdr1L_mid">2.89</td>
      <td class="bdr1L_mid">2.96</td>
      <td class="bdr1L_mid">3.04</td>
      <td class="bdr1L_mid">3.10</td>
      <td class="bdr1L_mid">3.17</td>
      <td class="bdr1L_mid">3.24</td>
    </tr>
    <tr>
      <td class="text_9_bold">55</td>
      <td class="bdr1L_mid">1.10</td>
      <td class="bdr1L_mid">1.17</td>
      <td class="bdr1L_mid">1.24</td>
      <td class="bdr1L_mid">1.31</td>
      <td class="bdr1L_mid">1.39</td>
      <td class="bdr1L_mid">1.46</td>
      <td class="bdr1L_mid">1.53</td>
      <td class="bdr1L_mid">1.60</td>
      <td class="bdr1L_mid">1.68</td>
      <td class="bdr1L_mid">1.75</td>
      <td class="bdr1L_mid">1.82</td>
      <td class="bdr1L_mid">1.89</td>
      <td class="bdr1L_mid">1.97</td>
      <td class="bdr1L_mid">2.04</td>
      <td class="bdr1L_mid">2.12</td>
      <td class="bdr1L_mid">2.18</td>
      <td class="bdr1L_mid">2.26</td>
      <td class="bdr1L_mid">2.33</td>
      <td class="bdr1L_mid">2.40</td>
      <td class="bdr1L_mid">2.47</td>
      <td class="bdr1L_mid">2.54</td>
      <td class="bdr1L_mid">2.62</td>
      <td class="bdr1L_mid">2.69</td>
      <td class="bdr1L_mid">2.76</td>
      <td class="bdr1L_mid">2.83</td>
      <td class="bdr1L_mid">2.89</td>
      <td class="bdr1L_mid">2.97</td>
      <td class="bdr1L_mid">3.04</td>
      <td class="bdr1L_mid">3.11</td>
      <td class="bdr1L_mid">3.18</td>
    </tr>
    <tr class="bknd_ultra_lt">
      <td class="text_9_bold">56</td>
      <td class="bdr1L_mid">1.07</td>
      <td class="bdr1L_mid">1.15</td>
      <td class="bdr1L_mid">1.22</td>
      <td class="bdr1L_mid">1.29</td>
      <td class="bdr1L_mid">1.36</td>
      <td class="bdr1L_mid">1.43</td>
      <td class="bdr1L_mid">1.50</td>
      <td class="bdr1L_mid">1.57</td>
      <td class="bdr1L_mid">1.65</td>
      <td class="bdr1L_mid">1.72</td>
      <td class="bdr1L_mid">1.79</td>
      <td class="bdr1L_mid">1.86</td>
      <td class="bdr1L_mid">1.93</td>
      <td class="bdr1L_mid">2.00</td>
      <td class="bdr1L_mid">2.08</td>
      <td class="bdr1L_mid">2.15</td>
      <td class="bdr1L_mid">2.22</td>
      <td class="bdr1L_mid">2.29</td>
      <td class="bdr1L_mid">2.36</td>
      <td class="bdr1L_mid">2.43</td>
      <td class="bdr1L_mid">2.50</td>
      <td class="bdr1L_mid">2.57</td>
      <td class="bdr1L_mid">2.64</td>
      <td class="bdr1L_mid">2.71</td>
      <td class="bdr1L_mid">2.78</td>
      <td class="bdr1L_mid">2.85</td>
      <td class="bdr1L_mid">2.92</td>
      <td class="bdr1L_mid">2.99</td>
      <td class="bdr1L_mid">3.06</td>
      <td class="bdr1L_mid">3.13</td>
    </tr>
    <tr>
      <td class="text_9_bold">57</td>
      <td class="bdr1L_mid">1.05</td>
      <td class="bdr1L_mid">1.12</td>
      <td class="bdr1L_mid">1.19</td>
      <td class="bdr1L_mid">1.26</td>
      <td class="bdr1L_mid">1.33</td>
      <td class="bdr1L_mid">1.40</td>
      <td class="bdr1L_mid">1.47</td>
      <td class="bdr1L_mid">1.54</td>
      <td class="bdr1L_mid">1.62</td>
      <td class="bdr1L_mid">1.70</td>
      <td class="bdr1L_mid">1.77</td>
      <td class="bdr1L_mid">1.83</td>
      <td class="bdr1L_mid">1.90</td>
      <td class="bdr1L_mid">1.97</td>
      <td class="bdr1L_mid">2.04</td>
      <td class="bdr1L_mid">2.11</td>
      <td class="bdr1L_mid">2.18</td>
      <td class="bdr1L_mid">2.25</td>
      <td class="bdr1L_mid">2.32</td>
      <td class="bdr1L_mid">2.39</td>
      <td class="bdr1L_mid">2.46</td>
      <td class="bdr1L_mid">2.53</td>
      <td class="bdr1L_mid">2.60</td>
      <td class="bdr1L_mid">2.66</td>
      <td class="bdr1L_mid">2.73</td>
      <td class="bdr1L_mid">2.80</td>
      <td class="bdr1L_mid">2.87</td>
      <td class="bdr1L_mid">2.94</td>
      <td class="bdr1L_mid">3.00</td>
      <td class="bdr1L_mid">3.08</td>
    </tr>
    <tr class="bknd_ultra_lt">
      <td class="text_9_bold">58</td>
      <td class="bdr1L_mid">1.03</td>
      <td class="bdr1L_mid">1.10</td>
      <td class="bdr1L_mid">1.17</td>
      <td class="bdr1L_mid">1.24</td>
      <td class="bdr1L_mid">1.30</td>
      <td class="bdr1L_mid">1.37</td>
      <td class="bdr1L_mid">1.44</td>
      <td class="bdr1L_mid">1.51</td>
      <td class="bdr1L_mid">1.59</td>
      <td class="bdr1L_mid">1.67</td>
      <td class="bdr1L_mid">1.74</td>
      <td class="bdr1L_mid">1.80</td>
      <td class="bdr1L_mid">1.87</td>
      <td class="bdr1L_mid">1.94</td>
      <td class="bdr1L_mid">2.01</td>
      <td class="bdr1L_mid">2.08</td>
      <td class="bdr1L_mid">2.15</td>
      <td class="bdr1L_mid">2.21</td>
      <td class="bdr1L_mid">2.28</td>
      <td class="bdr1L_mid">2.35</td>
      <td class="bdr1L_mid">2.42</td>
      <td class="bdr1L_mid">2.48</td>
      <td class="bdr1L_mid">2.55</td>
      <td class="bdr1L_mid">2.62</td>
      <td class="bdr1L_mid">2.69</td>
      <td class="bdr1L_mid">2.75</td>
      <td class="bdr1L_mid">2.82</td>
      <td class="bdr1L_mid">2.88</td>
      <td class="bdr1L_mid">2.95</td>
      <td class="bdr1L_mid">3.02</td>
    </tr>
    <tr>
      <td class="text_9_bold">59</td>
      <td class="bdr1L_mid">1.02</td>
      <td class="bdr1L_mid">1.09</td>
      <td class="bdr1L_mid">1.16</td>
      <td class="bdr1L_mid">1.22</td>
      <td class="bdr1L_mid">1.29</td>
      <td class="bdr1L_mid">1.36</td>
      <td class="bdr1L_mid">1.43</td>
      <td class="bdr1L_mid">1.49</td>
      <td class="bdr1L_mid">1.56</td>
      <td class="bdr1L_mid">1.64</td>
      <td class="bdr1L_mid">1.71</td>
      <td class="bdr1L_mid">1.77</td>
      <td class="bdr1L_mid">1.84</td>
      <td class="bdr1L_mid">1.91</td>
      <td class="bdr1L_mid">1.98</td>
      <td class="bdr1L_mid">2.04</td>
      <td class="bdr1L_mid">2.11</td>
      <td class="bdr1L_mid">2.17</td>
      <td class="bdr1L_mid">2.24</td>
      <td class="bdr1L_mid">2.31</td>
      <td class="bdr1L_mid">2.38</td>
      <td class="bdr1L_mid">2.43</td>
      <td class="bdr1L_mid">2.50</td>
      <td class="bdr1L_mid">2.57</td>
      <td class="bdr1L_mid">2.64</td>
      <td class="bdr1L_mid">2.70</td>
      <td class="bdr1L_mid">2.77</td>
      <td class="bdr1L_mid">2.84</td>
      <td class="bdr1L_mid">2.91</td>
      <td class="bdr1L_mid">2.97</td>
    </tr>
    <tr class="bknd_ultra_lt">
      <td class="text_9_bold">60</td>
      <td class="bdr1L_mid">1.01</td>
      <td class="bdr1L_mid">1.08</td>
      <td class="bdr1L_mid">1.15</td>
      <td class="bdr1L_mid">1.21</td>
      <td class="bdr1L_mid">1.28</td>
      <td class="bdr1L_mid">1.34</td>
      <td class="bdr1L_mid">1.41</td>
      <td class="bdr1L_mid">1.47</td>
      <td class="bdr1L_mid">1.54</td>
      <td class="bdr1L_mid">1.62</td>
      <td class="bdr1L_mid">1.68</td>
      <td class="bdr1L_mid">1.75</td>
      <td class="bdr1L_mid">1.82</td>
      <td class="bdr1L_mid">1.88</td>
      <td class="bdr1L_mid">1.95</td>
      <td class="bdr1L_mid">2.01</td>
      <td class="bdr1L_mid">2.08</td>
      <td class="bdr1L_mid">2.14</td>
      <td class="bdr1L_mid">2.21</td>
      <td class="bdr1L_mid">2.27</td>
      <td class="bdr1L_mid">2.34</td>
      <td class="bdr1L_mid">2.40</td>
      <td class="bdr1L_mid">2.47</td>
      <td class="bdr1L_mid">2.53</td>
      <td class="bdr1L_mid">2.60</td>
      <td class="bdr1L_mid">2.66</td>
      <td class="bdr1L_mid">2.73</td>
      <td class="bdr1L_mid">2.79</td>
      <td class="bdr1L_mid">2.86</td>
      <td class="bdr1L_mid">2.92</td>
    </tr>
    <tr>
      <td class="text_9_bold">61</td>
      <td class="bdr1L_mid">0.99</td>
      <td class="bdr1L_mid">1.05</td>
      <td class="bdr1L_mid">1.12</td>
      <td class="bdr1L_mid">1.18</td>
      <td class="bdr1L_mid">1.24</td>
      <td class="bdr1L_mid">1.31</td>
      <td class="bdr1L_mid">1.37</td>
      <td class="bdr1L_mid">1.44</td>
      <td class="bdr1L_mid">1.50</td>
      <td class="bdr1L_mid">1.57</td>
      <td class="bdr1L_mid">1.63</td>
      <td class="bdr1L_mid">1.69</td>
      <td class="bdr1L_mid">1.76</td>
      <td class="bdr1L_mid">1.82</td>
      <td class="bdr1L_mid">1.89</td>
      <td class="bdr1L_mid">1.95</td>
      <td class="bdr1L_mid">2.02</td>
      <td class="bdr1L_mid">2.08</td>
      <td class="bdr1L_mid">2.14</td>
      <td class="bdr1L_mid">2.21</td>
      <td class="bdr1L_mid">2.27</td>
      <td class="bdr1L_mid">2.34</td>
      <td class="bdr1L_mid">2.40</td>
      <td class="bdr1L_mid">2.47</td>
      <td class="bdr1L_mid">2.53</td>
      <td class="bdr1L_mid">2.59</td>
      <td class="bdr1L_mid">2.66</td>
      <td class="bdr1L_mid">2.72</td>
      <td class="bdr1L_mid">2.79</td>
      <td class="bdr1L_mid">2.85</td>
    </tr>
    <tr class="bknd_ultra_lt">
      <td class="text_9_bold">62</td>
      <td class="bdr1L_mid">0.96</td>
      <td class="bdr1L_mid">1.02</td>
      <td class="bdr1L_mid">1.09</td>
      <td class="bdr1L_mid">1.15</td>
      <td class="bdr1L_mid">1.21</td>
      <td class="bdr1L_mid">1.27</td>
      <td class="bdr1L_mid">1.34</td>
      <td class="bdr1L_mid">1.40</td>
      <td class="bdr1L_mid">1.46</td>
      <td class="bdr1L_mid">1.53</td>
      <td class="bdr1L_mid">1.59</td>
      <td class="bdr1L_mid">1.65</td>
      <td class="bdr1L_mid">1.71</td>
      <td class="bdr1L_mid">1.78</td>
      <td class="bdr1L_mid">1.84</td>
      <td class="bdr1L_mid">1.90</td>
      <td class="bdr1L_mid">1.97</td>
      <td class="bdr1L_mid">2.03</td>
      <td class="bdr1L_mid">2.09</td>
      <td class="bdr1L_mid">2.15</td>
      <td class="bdr1L_mid">2.22</td>
      <td class="bdr1L_mid">2.28</td>
      <td class="bdr1L_mid">2.34</td>
      <td class="bdr1L_mid">2.41</td>
      <td class="bdr1L_mid">2.47</td>
      <td class="bdr1L_mid">2.53</td>
      <td class="bdr1L_mid">2.59</td>
      <td class="bdr1L_mid">2.66</td>
      <td class="bdr1L_mid">2.72</td>
      <td class="bdr1L_mid">2.78</td>
    </tr>
    <tr>
      <td class="text_9_bold">63</td>
      <td class="bdr1L_mid">0.93</td>
      <td class="bdr1L_mid">0.99</td>
      <td class="bdr1L_mid">1.06</td>
      <td class="bdr1L_mid">1.12</td>
      <td class="bdr1L_mid">1.18</td>
      <td class="bdr1L_mid">1.24</td>
      <td class="bdr1L_mid">1.30</td>
      <td class="bdr1L_mid">1.36</td>
      <td class="bdr1L_mid">1.42</td>
      <td class="bdr1L_mid">1.49</td>
      <td class="bdr1L_mid">1.55</td>
      <td class="bdr1L_mid">1.61</td>
      <td class="bdr1L_mid">1.67</td>
      <td class="bdr1L_mid">1.73</td>
      <td class="bdr1L_mid">1.79</td>
      <td class="bdr1L_mid">1.85</td>
      <td class="bdr1L_mid">1.92</td>
      <td class="bdr1L_mid">1.98</td>
      <td class="bdr1L_mid">2.04</td>
      <td class="bdr1L_mid">2.10</td>
      <td class="bdr1L_mid">2.16</td>
      <td class="bdr1L_mid">2.22</td>
      <td class="bdr1L_mid">2.28</td>
      <td class="bdr1L_mid">2.35</td>
      <td class="bdr1L_mid">2.41</td>
      <td class="bdr1L_mid">2.47</td>
      <td class="bdr1L_mid">2.53</td>
      <td class="bdr1L_mid">2.59</td>
      <td class="bdr1L_mid">2.65</td>
      <td class="bdr1L_mid">2.71</td>
    </tr>
    <tr class="bknd_ultra_lt">
      <td class="text_9_bold">64</td>
      <td class="bdr1L_mid">0.91</td>
      <td class="bdr1L_mid">0.97</td>
      <td class="bdr1L_mid">1.03</td>
      <td class="bdr1L_mid">1.09</td>
      <td class="bdr1L_mid">1.15</td>
      <td class="bdr1L_mid">1.21</td>
      <td class="bdr1L_mid">1.27</td>
      <td class="bdr1L_mid">1.33</td>
      <td class="bdr1L_mid">1.39</td>
      <td class="bdr1L_mid">1.45</td>
      <td class="bdr1L_mid">1.51</td>
      <td class="bdr1L_mid">1.57</td>
      <td class="bdr1L_mid">1.63</td>
      <td class="bdr1L_mid">1.69</td>
      <td class="bdr1L_mid">1.75</td>
      <td class="bdr1L_mid">1.81</td>
      <td class="bdr1L_mid">1.87</td>
      <td class="bdr1L_mid">1.93</td>
      <td class="bdr1L_mid">1.99</td>
      <td class="bdr1L_mid">2.05</td>
      <td class="bdr1L_mid">2.11</td>
      <td class="bdr1L_mid">2.17</td>
      <td class="bdr1L_mid">2.23</td>
      <td class="bdr1L_mid">2.29</td>
      <td class="bdr1L_mid">2.35</td>
      <td class="bdr1L_mid">2.41</td>
      <td class="bdr1L_mid">2.47</td>
      <td class="bdr1L_mid">2.52</td>
      <td class="bdr1L_mid">2.58</td>
      <td class="bdr1L_mid">2.64</td>
    </tr>
    <tr>
      <td class="text_9_bold">65</td>
      <td class="bdr1L_mid">0.88</td>
      <td class="bdr1L_mid">0.94</td>
      <td class="bdr1L_mid">1.00</td>
      <td class="bdr1L_mid">1.06</td>
      <td class="bdr1L_mid">1.11</td>
      <td class="bdr1L_mid">1.17</td>
      <td class="bdr1L_mid">1.23</td>
      <td class="bdr1L_mid">1.29</td>
      <td class="bdr1L_mid">1.35</td>
      <td class="bdr1L_mid">1.41</td>
      <td class="bdr1L_mid">1.46</td>
      <td class="bdr1L_mid">1.52</td>
      <td class="bdr1L_mid">1.58</td>
      <td class="bdr1L_mid">1.64</td>
      <td class="bdr1L_mid">1.70</td>
      <td class="bdr1L_mid">1.76</td>
      <td class="bdr1L_mid">1.82</td>
      <td class="bdr1L_mid">1.87</td>
      <td class="bdr1L_mid">1.93</td>
      <td class="bdr1L_mid">1.99</td>
      <td class="bdr1L_mid">2.05</td>
      <td class="bdr1L_mid">2.11</td>
      <td class="bdr1L_mid">2.17</td>
      <td class="bdr1L_mid">2.23</td>
      <td class="bdr1L_mid">2.28</td>
      <td class="bdr1L_mid">2.34</td>
      <td class="bdr1L_mid">2.40</td>
      <td class="bdr1L_mid">2.46</td>
      <td class="bdr1L_mid">2.52</td>
      <td class="bdr1L_mid">2.58</td>
    </tr>
    <tr class="bknd_ultra_lt">
      <td class="text_9_bold">66</td>
      <td class="bdr1L_mid">0.85</td>
      <td class="bdr1L_mid">0.91</td>
      <td class="bdr1L_mid">0.97</td>
      <td class="bdr1L_mid">1.02</td>
      <td class="bdr1L_mid">1.08</td>
      <td class="bdr1L_mid">1.14</td>
      <td class="bdr1L_mid">1.20</td>
      <td class="bdr1L_mid">1.25</td>
      <td class="bdr1L_mid">1.31</td>
      <td class="bdr1L_mid">1.37</td>
      <td class="bdr1L_mid">1.42</td>
      <td class="bdr1L_mid">1.48</td>
      <td class="bdr1L_mid">1.54</td>
      <td class="bdr1L_mid">1.59</td>
      <td class="bdr1L_mid">1.65</td>
      <td class="bdr1L_mid">1.71</td>
      <td class="bdr1L_mid">1.77</td>
      <td class="bdr1L_mid">1.82</td>
      <td class="bdr1L_mid">1.88</td>
      <td class="bdr1L_mid">1.94</td>
      <td class="bdr1L_mid">1.99</td>
      <td class="bdr1L_mid">2.05</td>
      <td class="bdr1L_mid">2.11</td>
      <td class="bdr1L_mid">2.16</td>
      <td class="bdr1L_mid">2.22</td>
      <td class="bdr1L_mid">2.28</td>
      <td class="bdr1L_mid">2.34</td>
      <td class="bdr1L_mid">2.39</td>
      <td class="bdr1L_mid">2.45</td>
      <td class="bdr1L_mid">2.51</td>
    </tr>
    <tr>
      <td class="text_9_bold">67</td>
      <td class="bdr1L_mid">0.83</td>
      <td class="bdr1L_mid">0.88</td>
      <td class="bdr1L_mid">0.94</td>
      <td class="bdr1L_mid">0.99</td>
      <td class="bdr1L_mid">1.05</td>
      <td class="bdr1L_mid">1.10</td>
      <td class="bdr1L_mid">1.16</td>
      <td class="bdr1L_mid">1.22</td>
      <td class="bdr1L_mid">1.27</td>
      <td class="bdr1L_mid">1.33</td>
      <td class="bdr1L_mid">1.38</td>
      <td class="bdr1L_mid">1.44</td>
      <td class="bdr1L_mid">1.49</td>
      <td class="bdr1L_mid">1.55</td>
      <td class="bdr1L_mid">1.60</td>
      <td class="bdr1L_mid">1.66</td>
      <td class="bdr1L_mid">1.72</td>
      <td class="bdr1L_mid">1.77</td>
      <td class="bdr1L_mid">1.83</td>
      <td class="bdr1L_mid">1.88</td>
      <td class="bdr1L_mid">1.94</td>
      <td class="bdr1L_mid">1.99</td>
      <td class="bdr1L_mid">2.05</td>
      <td class="bdr1L_mid">2.10</td>
      <td class="bdr1L_mid">2.16</td>
      <td class="bdr1L_mid">2.22</td>
      <td class="bdr1L_mid">2.27</td>
      <td class="bdr1L_mid">2.33</td>
      <td class="bdr1L_mid">2.38</td>
      <td class="bdr1L_mid">2.44</td>
    </tr>
    <tr class="bknd_ultra_lt">
      <td class="text_9_bold">68</td>
      <td class="bdr1L_mid">0.80</td>
      <td class="bdr1L_mid">0.85</td>
      <td class="bdr1L_mid">0.91</td>
      <td class="bdr1L_mid">0.96</td>
      <td class="bdr1L_mid">1.02</td>
      <td class="bdr1L_mid">1.07</td>
      <td class="bdr1L_mid">1.12</td>
      <td class="bdr1L_mid">1.18</td>
      <td class="bdr1L_mid">1.23</td>
      <td class="bdr1L_mid">1.29</td>
      <td class="bdr1L_mid">1.34</td>
      <td class="bdr1L_mid">1.39</td>
      <td class="bdr1L_mid">1.45</td>
      <td class="bdr1L_mid">1.50</td>
      <td class="bdr1L_mid">1.56</td>
      <td class="bdr1L_mid">1.61</td>
      <td class="bdr1L_mid">1.67</td>
      <td class="bdr1L_mid">1.72</td>
      <td class="bdr1L_mid">1.77</td>
      <td class="bdr1L_mid">1.83</td>
      <td class="bdr1L_mid">1.88</td>
      <td class="bdr1L_mid">1.94</td>
      <td class="bdr1L_mid">1.99</td>
      <td class="bdr1L_mid">2.04</td>
      <td class="bdr1L_mid">2.10</td>
      <td class="bdr1L_mid">2.15</td>
      <td class="bdr1L_mid">2.21</td>
      <td class="bdr1L_mid">2.26</td>
      <td class="bdr1L_mid">2.32</td>
      <td class="bdr1L_mid">2.37</td>
    </tr>
    <tr>
      <td class="text_9_bold">69</td>
      <td class="bdr1L_mid">0.77</td>
      <td class="bdr1L_mid">0.83</td>
      <td class="bdr1L_mid">0.88</td>
      <td class="bdr1L_mid">0.93</td>
      <td class="bdr1L_mid">0.98</td>
      <td class="bdr1L_mid">1.04</td>
      <td class="bdr1L_mid">1.09</td>
      <td class="bdr1L_mid">1.14</td>
      <td class="bdr1L_mid">1.19</td>
      <td class="bdr1L_mid">1.25</td>
      <td class="bdr1L_mid">1.30</td>
      <td class="bdr1L_mid">1.35</td>
      <td class="bdr1L_mid">1.40</td>
      <td class="bdr1L_mid">1.46</td>
      <td class="bdr1L_mid">1.51</td>
      <td class="bdr1L_mid">1.56</td>
      <td class="bdr1L_mid">1.62</td>
      <td class="bdr1L_mid">1.67</td>
      <td class="bdr1L_mid">1.72</td>
      <td class="bdr1L_mid">1.77</td>
      <td class="bdr1L_mid">1.83</td>
      <td class="bdr1L_mid">1.88</td>
      <td class="bdr1L_mid">1.93</td>
      <td class="bdr1L_mid">1.98</td>
      <td class="bdr1L_mid">2.04</td>
      <td class="bdr1L_mid">2.09</td>
      <td class="bdr1L_mid">2.14</td>
      <td class="bdr1L_mid">2.20</td>
      <td class="bdr1L_mid">2.25</td>
      <td class="bdr1L_mid">2.30</td>
    </tr>
    <tr class="bknd_ultra_lt">
      <td class="text_9_bold">70</td>
      <td class="bdr1L_mid">0.75</td>
      <td class="bdr1L_mid">0.80</td>
      <td class="bdr1L_mid">0.85</td>
      <td class="bdr1L_mid">0.90</td>
      <td class="bdr1L_mid">0.95</td>
      <td class="bdr1L_mid">1.00</td>
      <td class="bdr1L_mid">1.05</td>
      <td class="bdr1L_mid">1.10</td>
      <td class="bdr1L_mid">1.16</td>
      <td class="bdr1L_mid">1.21</td>
      <td class="bdr1L_mid">1.26</td>
      <td class="bdr1L_mid">1.31</td>
      <td class="bdr1L_mid">1.36</td>
      <td class="bdr1L_mid">1.41</td>
      <td class="bdr1L_mid">1.46</td>
      <td class="bdr1L_mid">1.51</td>
      <td class="bdr1L_mid">1.57</td>
      <td class="bdr1L_mid">1.62</td>
      <td class="bdr1L_mid">1.67</td>
      <td class="bdr1L_mid">1.72</td>
      <td class="bdr1L_mid">1.77</td>
      <td class="bdr1L_mid">1.82</td>
      <td class="bdr1L_mid">1.87</td>
      <td class="bdr1L_mid">1.92</td>
      <td class="bdr1L_mid">1.98</td>
      <td class="bdr1L_mid">2.03</td>
      <td class="bdr1L_mid">2.08</td>
      <td class="bdr1L_mid">2.13</td>
      <td class="bdr1L_mid">2.18</td>
      <td class="bdr1L_mid">2.23</td>
    </tr>
</table>
</div>
<?php include ('../includes/footer2.inc.php'); ?>
</body>
</html>
